app/views/__init__.py
from flask import Blueprint

bp = Blueprint("views", __name__, template_folder="templates")

from .routes import login

app/views/routes/login.py
from flask import render_template, url_for, request, redirect
from app import db
from .. import bp as views
from app.models import models
from flask_security import login_required, login_user, current_user


@views.route("/login", methods=["GET", "POST"])
def views_login():
    if request.method == "POST":
        email = request.form.get("email")
        pwd = request.form.get("password")

        data = models.User.query.filter_by(email=email).first()

        if data is not None:
            if data.check_password(pwd):
                login_user(data)
                return redirect(url_for("views.views_dashboard"))
            else:
                print("Pasw")

    return render_template("auth/login.html")


@views.route("/dashboard")
@login_required
def views_dashboard():
    return render_template("dashboard.html")


@views.route("/dashboard/user", methods=["GET", "POST"])
@login_required
def views_user():
    user = models.User.query.first()
    return render_template("user.html", user=user)


@views.route("/dashboard/company-profile", methods=["GET", "POST"])
@login_required
def views_company_profile():
    data = models.Company_Profile.query.first()
    if request.method == "POST":
        name = request.form.get("name")
        company_type = request.form.get("company_type")
        address = request.form.get("address")
        province = request.form.get("province")
        country = request.form.get("country")
        postal_code = request.form.get("postal_code")
        email = request.form.get("email")
        website = request.form.get("website")
        phone_number = request.form.get("phone")
        description = request.form.get("description")
        instagram = request.form.get("instagram")
        facebook = request.form.get("facebook")
        twitter = request.form.get("twitter")
        photo = request.files["photo"]
        logo = request.files["logo"]

        data.name = name
        data.company_type = company_type
        data.address = address
        data.province = province
        data.country = country
        data.postal_code = postal_code
        data.email = email
        data.website = website
        data.phone_number = phone_number
        data.instagram = instagram
        data.twitter = twitter
        data.facebook = facebook
        data.description = description
        data.image = photo.read()
        data.image_name = photo.filename
        data.logo = logo.read()
        data.logo_name = logo.filename

        db.session.add(data)
        db.session.commit()
        return redirect(url_for(".views_company_profile"))
    return render_template("company_profile.html", company_profile=data)


@views.route("/dashboard/portofolio")
@login_required
def views_portofolio():
    data = models.Portfolio.query.filter_by(user_id=current_user.id).all()
    return render_template("portofolios.html", data=data)


@views.route("/dashboard/tambah-portofolio", methods=["GET", "POST"])
@login_required
def views_tambah_portofolio():
    if request.method == "POST":
        data = models.Portfolio(
            user_id=current_user.id,
            title=request.form.get("title"),
            dev_names=request.form.get("dev_names"),
            category=request.form.get("category"),
            photo=request.files["photo"].read(),
            photo_name=request.files["photo"].filename,
            technology=request.form.get("technology"),
            link=request.form.get("link"),
            description=request.form.get("description"),
        )

        db.session.add(data)
        db.session.commit()
        return redirect(url_for(".views_portofolio"))
    return render_template("tambah_portfolio.html")


@views.route("/dashboard/<id>/edit-portofolio", methods=["GET", "POST"])
@login_required
def views_edit_portofolio(id):
    data = models.Portfolio.query.get(id)

    if request.method == "POST":
        title = request.form.get("title")
        dev_names = request.form.get("dev_names")
        category = request.form.get("category")
        photo = request.files["photo"].read()
        photo_name = request.files["photo"].filename
        technology = request.form.get("technology")
        link = request.form.get("link")
        description = request.form.get("description")

        data.title = title
        data.dev_names = dev_names
        data.category = category
        data.photo = photo
        data.photo_name = photo_name
        data.technology = technology
        data.link = link
        data.description = description

        db.session.add(data)
        db.session.commit()
        return redirect(url_for(".views_portofolio"))

    return render_template("edit_portfolio.html", data=data)


@views.route("/dashboard/<id>/hapus-portofolio", methods=["GET", "POST"])
@login_required
def views_hapus_portofolio(id):
    data = models.Portfolio.query.get(id)
    db.session.delete(id)
    db.session.commit()
    return redirect(url_for(".views_portofolio"))

app/views/templates/company_profile.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Company Profile</title>
    <style>
        .form {
            display: flex;
            flex-direction: column;
        }
    </style>
</head>

<body>
    <a href="{{ url_for('views.views_dashboard')}}">Dashboard</a>
    <a href="{{ url_for('views.views_user')}}">User</a>
    <a href="{{ url_for('views.views_company_profile')}}">Company Profile</a>
    <a href="{{ url_for('views.views_portofolio') }}">Portfolio</a>
    <hr>

    <div class="company">
        <form method="post" class="form" enctype=multipart/form-data> <label for="name">Name</label>
            <input type="text" name="name" placeholder="{{ company_profile.name }}">
            <label for="company_type">Company Type</label>
            <input type="text" name="company_type" placeholder="{{ company_profile.company_type }}">
            <label for="address">Address</label>
            <textarea name="address" placeholder="{{ company_profile.address }}"></textarea>
            <label for="province">Province</label>
            <input type="text" name="province" placeholder="{{ company_profile.province }}">
            <label for="country">Country</label>
            <input type="text" name="country" placeholder="{{ company_profile.country }}">
            <label for="postal_code">Postal Code</label>
            <input type="text" name="postal_code" placeholder="{{ company_profile.postal_code }}">
            <label for="email">Email</label>
            <input type="email" name="email" placeholder="{{ company_profile.email }}">
            <label for="website">Website</label>
            <input type="url" name="website" placeholder="{{ company_profile.website }}">
            <label for="phone">Phone Number</label>
            <input type="tel" name="phone" placeholder="{{ company_profile.phone_number }}">
            <label for="instagram">Instagram</label>
            <input type="url" name="instagram" placeholder="{{ company_profile.instagram}}">
            <label for="facebook">Facebook</label>
            <input type="url" name="facebook" placeholder="{{ company_profile.facebook}}">
            <label for="twitter">Twitter</label>
            <input type="url" name="twitter" placeholder="{{ company_profile.twitter}}"">
            <label for="photo">Image For Header</label>
            <input type="file" name="photo">
            <label for="logo">Logo for favicon</label>
            <input type="file" name="logo">
            <label for="description">Description</label>
            <textarea name="description" placeholder="{{ company_profile.description }}"></textarea>
            <button type="submit">Submit</button>
        </form>
    </div>
</body>

</html>

app/views/templates/dashboard.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Dashboard</title>
</head>
<body>
    <a href="{{ url_for('views.views_dashboard')}}">Dashboard</a>
    <a href="{{ url_for('views.views_user')}}">User</a>
    <a href="{{ url_for('views.views_company_profile')}}">Company Profile</a>
    <a href="{{ url_for('views.views_portofolio') }}">Portfolio</a>
    <hr>
</body>
</html>

app/views/templates/edit_portfolio.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Company Profile</title>
    <style>
        .form {
            display: flex;
            flex-direction: column;
        }
    </style>
</head>

<body>
    <a href="{{ url_for('views.views_dashboard')}}">Dashboard</a>
    <a href="{{ url_for('views.views_user')}}">User</a>
    <a href="{{ url_for('views.views_company_profile')}}">Company Profile</a>
    <a href="{{ url_for('views.views_portofolio') }}">Portfolio</a>
    <hr>
    <a href="{{ url_for('views.views_portofolio') }}">Back</a>

    <div class="user">
        <form method="post" class="form" enctype="multipart/form-data">
            <label for="title">Title</label>
            <input type="text" name="title" placeholder="{{data.title}}">
            <label for="dev_names">Developer Names</label>
            <input type="text" name="dev_names" placeholder="{{data.dev_names}}">
            <label for="photo">Photo</label>
            <input type="file" name="photo">
            <label for="category">Category</label>
            <input type="text" name="category" placeholder={{data.category}}>
            <label for="technology">Technology</label>
            <input type="text" name="technology" placeholder="{{data.technology}}">
            <label for="link">Link</label>
            <input type="url" name="link" placeholder="{{ data.link}}">
            <label for="description">Description</label>
            <textarea name="description" cols="30" rows="10" placeholder="{{ data.description}}"></textarea>
            <button type="submit">Submit</button>
        </form>
    </div>
</body>

</html>

app/views/templates/portofolios.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Portfolios</title>
</head>

<body>
    <a href="{{ url_for('views.views_dashboard')}}">Dashboard</a>
    <a href="{{ url_for('views.views_user')}}">User</a>
    <a href="{{ url_for('views.views_company_profile')}}">Company Profile</a>
    <a href="{{ url_for('views.views_portofolio') }}">Portfolio</a>
    <hr>

    <a href="{{ url_for('views.views_tambah_portofolio')}}">Tambah Portfolio</a>
    <table>
        <tr>
            <th>No.</th>
            <th>Portfolios Name</th>
            <th>Dev. Names</th>
            <th>Action</th>
        </tr>
        <tr>
            {% for data in data %}
            <td>{{ loop.index }}</td>
            <td>{{ data.title }}</td>
            <td>{{ data.dev_names }}</td>
            <td><a href="{{ url_for('views.views_edit_portofolio', id=data.id )}}">Edit</a>
            <td><a href="{{ url_for('views.views_hapus_portofolio', id=data.id )}}">Hapus</a></td>
            {% endfor %}
        </tr>
    </table>
</body>

</html>

app/views/templates/tambah_portfolio.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Company Profile</title>
    <style>
        .form {
            display: flex;
            flex-direction: column;
        }
    </style>
</head>

<body>
    <a href="{{ url_for('views.views_dashboard')}}">Dashboard</a>
    <a href="{{ url_for('views.views_user')}}">User</a>
    <a href="{{ url_for('views.views_company_profile')}}">Company Profile</a>
    <a href="{{ url_for('views.views_portofolio') }}">Portfolio</a>
    <hr>
    <a href="{{ url_for('views.views_portofolio') }}">Back</a>

    <div class="user">
        <form method="post" class="form" enctype="multipart/form-data">
            <label for="title">Title</label>
            <input type="text" name="title">
            <label for="dev_names">Developer Names</label>
            <input type="text" name="dev_names">
            <label for="photo">Photo</label>
            <input type="file" name="photo">
            <label for="category">Category</label>
            <input type="text" name="category">
            <label for="technology">Technology</label>
            <input type="text" name="technology">
            <label for="link">Link</label>
            <input type="url" name="link">
            <label for="description">Description</label>
            <textarea name="description" cols="30" rows="10"></textarea>
            <button type="submit">Submit</button>
        </form>
    </div>

</body>

</html>

app/views/templates/user.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Company Profile</title>
    <style>
        .form {
            display: flex;
            flex-direction: column;
        }
    </style>
</head>

<body>
    <a href="{{ url_for('views.views_dashboard')}}">Dashboard</a>
    <a href="{{ url_for('views.views_user')}}">User</a>
    <a href="{{ url_for('views.views_company_profile')}}">Company Profile</a>
    <a href="{{ url_for('views.views_portofolio') }}">Portfolio</a>
    <hr>
    <div class="user">
        <form method="post" class="form">
            <label for="name">Name</label>
            <input type="text" name="name" placeholder="{{ user.name }}">
            <label for="username">Username</label>
            <input type="text" name="username" placeholder="{{ user.username }}">
            <label for="email">Email</label>
            <input type="email" name="email" placeholder="{{ user.email }}">
            <label for="password">Password</label>
            <input type="password" name="password">
            <label for="master">Skills</label>
            <input type="text" name="master" placeholder="{{ user.master }}">
            <label for="photo">Photo</label>
            <input type="file" name="photo">
            <label for="instagram">Instagram</label>
            <input type="url" name="instagram">
            <label for="facebook">Facebook</label>
            <input type="url" name="facebook">
            <label for="twitter">Twitter</label>
            <input type="url" name="twitter">
        </form>
    </div>
</body>

</html>